# base image for ASP.NET Core
# automatically exposes PORT 80
FROM microsoft/aspnetcore

# install nodejs for angular, webpack middleware
RUN apt-get update  
RUN apt-get -f install  
RUN apt-get install -y wget  
RUN wget -qO- https://deb.nodesource.com/setup_9.x | bash -  
RUN apt-get install -y build-essential nodejs

WORKDIR /app
COPY ./src/Callisto.Web.App/bin/Release/netcoreapp2.0/publish/  .
ENTRYPOINT ["dotnet", "Callisto.Web.App.dll"]
