# base image for ASP.NET Core
# automatically exposes PORT 80
FROM microsoft/mssql-server-linux

ENV ACCEPT_EULA="Y"
ENV SA_PASSWORD="Password!2"
ENV DATABASE="TEST"
ENV USER="docker"
ENV PASS="Password!2"

COPY setup.sql .

RUN /opt/mssql/bin/sqlservr --accept-eula & sleep 10 \
    && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -i setup.sql \
    && pkill sqlservr 

