version: '3.3'

services:
  landing:
    image: hermancombrink/callisto-landing
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks: 
      - default

  api:
    image: hermancombrink/callisto-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks: 
      - default

  app:
    image: hermancombrink/callisto-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks: 
      - default

  nginx:
    image: hermancombrink/callisto-nginx
    depends_on:
      - landing
      - api
      - app
    ports:
      - "8000:80"
    networks:
      - default
   
#  sql:
#    image: hermancombrink/callisto-sql
#    build: 
#      context: docker/sql/
#      dockerfile: dockerfile
#    networks: 
#      - default
#    ports:
#      - "8001:1433"   
#    volumes: 
#      - sqlvolume:/var/opt/mssql

  rabbit:
    image: hermancombrink/callisto-rabbitmq
    networks: 
      - default
    ports:
      - "8002:15672"  
    volumes:
      - rabbitvolume:/var/lib/rabbitmq

  prometheus:
    image: hermancombrink/callisto-prometheus
    ports:
      - "8003:9090"
    networks:
      - default

  grafana:
    image: hermancombrink/callisto-grafana
    ports:
      - "8004:3000"
    networks:
      - default

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "8005:9000"

volumes:
#  sqlvolume:
  rabbitvolume:
  portainer_data:

networks:
  default:
