version: '3.3'

services:
  landing:
    image: hermancombrink/callisto-landing
    environment:
      - ASPNETCORE_ENVIRONMENT=Azure
    networks: 
      - default

  api:
    image: hermancombrink/callisto-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Azure
    networks: 
      - default

  app:
    image: hermancombrink/callisto-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Azure
    networks: 
      - default

  worker:
    image: hermancombrink/callisto-worker
    environment:
      - ASPNETCORE_ENVIRONMENT=Azure
    networks: 
      - default

  nginx:
    image: hermancombrink/callisto-nginx
    depends_on:
      - landing
      - api
      - app
    ports:
      - "80:80"
    networks:
      - default
   
  rabbit:
    image: hermancombrink/callisto-rabbitmq
    networks: 
      - default
    ports:
      - "8083:15672"  
    volumes:
      - rabbitvolume:/var/lib/rabbitmq

  prometheus:
    image: hermancombrink/callisto-prometheus
    networks:
      - default

  grafana:
    image: hermancombrink/callisto-grafana
    ports:
      - "8082:3000"
    networks:
      - default

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "8081:9000"

volumes:
  rabbitvolume:
  portainer_data:

networks:
  default:
