version: '3.3'

services:
  landing:
    build:
      context: src/Callisto.Web.Landing/
      dockerfile: dockerfile

  api:
    build:
      context: src/Callisto.Web.Api/
      dockerfile: dockerfile

  app:
    build:
      context: src/Callisto.Web.App/
      dockerfile: dockerfile

  worker:
    build:
      context: src/Callisto.Worker.Service/
      dockerfile: dockerfile

  nginx: 
    build: 
      context: docker/nginx/
      dockerfile: dockerfile

  rabbit: 
    build: 
      context: docker/rabbitmq/
      dockerfile: dockerfile

  prometheus: 
    build: 
      context: docker/prometheus/
      dockerfile: dockerfile

  grafana: 
    build: 
      context: docker/grafana/
      dockerfile: dockerfile
