version: '3.3'

services:
  landing:
    image: hermancombrink/callisto-landing
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks: 
      - default

  api:
    image: hermancombrink/callisto-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks: 
      - default

  app:
    image: hermancombrink/callisto-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks: 
      - default

  nginx:
    image: hermancombrink/callisto-nginx
    depends_on:
      - landing
      - api
      - app
    ports:
      - "80:80"
    networks:
      - default

  sql:
    image: hermancombrink/callisto-sql
    networks: 
      - default
    ports:
      - "1434:1433"   

  rabbit:
    image: hermancombrink/callisto-rabbitmq
    networks: 
      - default
    ports:
      - "15673:15672"  

networks:
  default:
