version: '3.3'

services:
  landing:
    image: hermancombrink/callisto-landing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks: 
      - default

  nginx:
    image: hermancombrink/callisto-nginx
    depends_on:
      - landing
    ports:
      - "8090:80"
    networks:
      - default

networks:
  default:
    external:
      name: nat

