FROM microsoft/aspnetcore-build AS build
WORKDIR /app
COPY ./src/Callisto.Web.Landing/bin/Release/netcoreapp2.0/publish/ .
WORKDIR /app/wwwroot
RUN npm install

FROM microsoft/aspnetcore
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Callisto.Web.Landing.dll"]
