CREATE TABLE [callisto].[Assets]
(
	[RefId] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), 
    [CreatedAt] DATETIME NULL DEFAULT GETDATE(), 
    [ModifiedAt] DATETIME NULL DEFAULT GETDATE(),
	[AssetNumber] NVARCHAR(256) NULL, 
	[Name] NVARCHAR(256) NULL, 
    [Description] NVARCHAR(512) NULL,
	[CompanyRefId] BIGINT NOT NULL, 
    [ParrentAssetRefId] BIGINT NULL
)
GO

ALTER TABLE [callisto].[Assets]  WITH CHECK ADD  CONSTRAINT [FK_Assets_Companies] FOREIGN KEY([CompanyRefId])
REFERENCES [callisto].[Companies] ([RefId])
GO

ALTER TABLE [callisto].[Assets] CHECK CONSTRAINT [FK_Assets_Companies]
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_Asset_Id] ON [callisto].[Assets]
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO